// <auto-generated />
using System;
using ECommerce.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Api.Data.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260914211944_AddPaymentsAndOrderCurrency")]
    partial class AddPaymentsAndOrderCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ECommerce.Api.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("ECommerce.Api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity_Valid", "\"Quantity\" BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_IsActive_Valid", "\"IsActive\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Categories_Name_Valid", "length(trim(\"Name\")) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomerAddresses_CustomerId_Default")
                        .HasFilter("\"IsDefault\" = 1");

                    b.HasIndex("CustomerId", "UpdatedAtUtc");

                    b.ToTable("CustomerAddresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerAddresses_AddressLine1_Valid", "length(trim(\"AddressLine1\")) BETWEEN 5 AND 300");

                            t.HasCheckConstraint("CK_CustomerAddresses_AddressLine2_Valid", "\"AddressLine2\" IS NULL OR length(trim(\"AddressLine2\")) BETWEEN 1 AND 300");

                            t.HasCheckConstraint("CK_CustomerAddresses_City_Valid", "length(trim(\"City\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_CustomerAddresses_CountryCode_Valid", "length(\"CountryCode\") = 2 AND \"CountryCode\" = upper(\"CountryCode\")");

                            t.HasCheckConstraint("CK_CustomerAddresses_District_Valid", "length(trim(\"District\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_CustomerAddresses_IsDefault_Valid", "\"IsDefault\" IN (0, 1)");

                            t.HasCheckConstraint("CK_CustomerAddresses_Label_Valid", "length(trim(\"Label\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_CustomerAddresses_PhoneNumber_Valid", "length(trim(\"PhoneNumber\")) BETWEEN 3 AND 30");

                            t.HasCheckConstraint("CK_CustomerAddresses_PostalCode_Valid", "length(trim(\"PostalCode\")) BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_CustomerAddresses_RecipientFullName_Valid", "length(trim(\"RecipientFullName\")) BETWEEN 2 AND 200");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("TRY")
                        .IsFixedLength();

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "CreatedAtUtc");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Currency_Valid", "length(\"Currency\") = 3 AND \"Currency\" = upper(\"Currency\")");

                            t.HasCheckConstraint("CK_Orders_CustomerEmail_Valid", "length(trim(\"CustomerEmail\")) BETWEEN 3 AND 254");

                            t.HasCheckConstraint("CK_Orders_ShippingAddressLine1_Valid", "\"ShippingAddressLine1\" IS NULL OR length(trim(\"ShippingAddressLine1\")) BETWEEN 5 AND 300");

                            t.HasCheckConstraint("CK_Orders_ShippingAddressLine2_Valid", "\"ShippingAddressLine2\" IS NULL OR length(trim(\"ShippingAddressLine2\")) BETWEEN 1 AND 300");

                            t.HasCheckConstraint("CK_Orders_ShippingAddress_Complete", "(\"ShippingRecipientFullName\" IS NULL AND \"ShippingPhoneNumber\" IS NULL AND \"ShippingAddressLine1\" IS NULL AND \"ShippingAddressLine2\" IS NULL AND \"ShippingDistrict\" IS NULL AND \"ShippingCity\" IS NULL AND \"ShippingPostalCode\" IS NULL AND \"ShippingCountryCode\" IS NULL) OR (\"ShippingRecipientFullName\" IS NOT NULL AND \"ShippingPhoneNumber\" IS NOT NULL AND \"ShippingAddressLine1\" IS NOT NULL AND \"ShippingDistrict\" IS NOT NULL AND \"ShippingCity\" IS NOT NULL AND \"ShippingPostalCode\" IS NOT NULL AND \"ShippingCountryCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Orders_ShippingCity_Valid", "\"ShippingCity\" IS NULL OR length(trim(\"ShippingCity\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Orders_ShippingCountryCode_Valid", "\"ShippingCountryCode\" IS NULL OR (length(\"ShippingCountryCode\") = 2 AND \"ShippingCountryCode\" = upper(\"ShippingCountryCode\"))");

                            t.HasCheckConstraint("CK_Orders_ShippingDistrict_Valid", "\"ShippingDistrict\" IS NULL OR length(trim(\"ShippingDistrict\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Orders_ShippingPhoneNumber_Valid", "\"ShippingPhoneNumber\" IS NULL OR length(trim(\"ShippingPhoneNumber\")) BETWEEN 3 AND 30");

                            t.HasCheckConstraint("CK_Orders_ShippingPostalCode_Valid", "\"ShippingPostalCode\" IS NULL OR length(trim(\"ShippingPostalCode\")) BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Orders_ShippingRecipientFullName_Valid", "\"ShippingRecipientFullName\" IS NULL OR length(trim(\"ShippingRecipientFullName\")) BETWEEN 2 AND 200");

                            t.HasCheckConstraint("CK_Orders_Status_Valid", "\"Status\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_Orders_TotalAmount_Positive", "CAST(\"TotalAmount\" AS NUMERIC) > 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_LineTotal_Positive", "CAST(\"LineTotal\" AS NUMERIC) > 0");

                            t.HasCheckConstraint("CK_OrderItems_ProductName_Valid", "length(trim(\"ProductName\")) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_OrderItems_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPrice_Positive", "CAST(\"UnitPrice\" AS NUMERIC) > 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_OrderId_Active")
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.HasIndex("OrderId", "CreatedAtUtc");

                    b.HasIndex("OrderId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount_Positive", "CAST(\"Amount\" AS NUMERIC) > 0");

                            t.HasCheckConstraint("CK_Payments_Currency_Valid", "length(\"Currency\") = 3 AND \"Currency\" = upper(\"Currency\")");

                            t.HasCheckConstraint("CK_Payments_IdempotencyKey_Valid", "length(trim(\"IdempotencyKey\")) BETWEEN 8 AND 100");

                            t.HasCheckConstraint("CK_Payments_Provider_Valid", "length(trim(\"Provider\")) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Payments_RequestFingerprint_Valid", "length(\"RequestFingerprint\") = 64");

                            t.HasCheckConstraint("CK_Payments_Result_Consistent", "(\"Status\" = 1 AND \"ProviderPaymentId\" IS NULL AND \"FailureCode\" IS NULL) OR (\"Status\" = 2 AND \"ProviderPaymentId\" IS NOT NULL AND \"FailureCode\" IS NULL) OR (\"Status\" = 3 AND \"FailureCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Payments_Status_Valid", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_IsActive_Valid", "\"IsActive\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Products_Name_Valid", "length(trim(\"Name\")) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_Products_Price_Positive", "CAST(\"Price\" AS NUMERIC) > 0");

                            t.HasCheckConstraint("CK_Products_StockQuantity_NonNegative", "\"StockQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Api.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantityAfter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CreatedAtUtc");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockMovements_QuantityDelta_NonZero", "\"QuantityDelta\" <> 0");

                            t.HasCheckConstraint("CK_StockMovements_Reason_Valid", "length(trim(\"Reason\")) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_StockMovements_StockQuantityAfter_NonNegative", "\"StockQuantityAfter\" >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Api.Models.Cart", b =>
                {
                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("ECommerce.Api.Models.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerce.Api.Models.CartItem", b =>
                {
                    b.HasOne("ECommerce.Api.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Api.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Api.Models.CustomerAddress", b =>
                {
                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Order", b =>
                {
                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("ECommerce.Api.Models.OrderAddressSnapshot", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingAddressLine1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingAddressLine2");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingCity");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingCountryCode")
                                .IsFixedLength();

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingDistrict");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingPhoneNumber");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingPostalCode");

                            b1.Property<string>("RecipientFullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingRecipientFullName");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("ECommerce.Api.Models.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Api.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Payment", b =>
                {
                    b.HasOne("ECommerce.Api.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Product", b =>
                {
                    b.HasOne("ECommerce.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Api.Models.StockMovement", b =>
                {
                    b.HasOne("ECommerce.Api.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ECommerce.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Api.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ECommerce.Api.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
